ALTER TABLE users 
ADD COLUMN IF NOT EXISTS auto_meeting_sync BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS ai_insights BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS auto_task_gen BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS email_notifs BOOLEAN DEFAULT true;
